# Generated by Django 3.1.6 on 2023-11-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('url', models.TextField(blank=True, null=True)),
                ('wskeycount', models.IntegerField()),
                ('ckcount', models.IntegerField()),
                ('wpapptoken', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('clientid', models.TextField(blank=True, null=True)),
                ('clientsecret', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'containers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efmigrationshistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migrationid', models.TextField(db_column='MigrationId')),
                ('productversion', models.TextField(db_column='ProductVersion')),
            ],
            options={
                'db_table': '__EFMigrationsHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pin', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('wskey', models.TextField(blank=True, null=True)),
                ('ckvalue', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('imgurl', models.TextField(blank=True, null=True)),
                ('uuid', models.TextField(blank=True, null=True)),
                ('expired', models.IntegerField()),
                ('status', models.IntegerField()),
                ('envt', models.IntegerField(db_column='Envt')),
                ('position', models.IntegerField()),
                ('containerid', models.IntegerField()),
            ],
            options={
                'db_table': 'Env',
                'managed': False,
            },
        ),
    ]
